UPDATE [dbo].[post] SET [type] = '2' WHERE post_id=1
UPDATE [dbo].[post] SET [type] = '2' WHERE post_id=2
UPDATE [dbo].[post] SET [type] = '4' WHERE post_id=3
UPDATE [dbo].[post] SET [type] = '1' WHERE post_id=4
UPDATE [dbo].[post] SET [type] = '4' WHERE post_id=5
UPDATE [dbo].[post] SET [type] = '2' WHERE post_id=6
UPDATE [dbo].[post] SET [type] = '1' WHERE post_id=7
UPDATE [dbo].[post] SET [type] = '3' WHERE post_id=8
UPDATE [dbo].[post] SET [type] = '1' WHERE post_id=9
UPDATE [dbo].[post] SET [type] = '2' WHERE post_id=10
UPDATE [dbo].[post] SET [type] = '4' WHERE post_id=11
UPDATE [dbo].[post] SET [type] = '2' WHERE post_id=12
UPDATE [dbo].[post] SET [type] = '4' WHERE post_id=13
UPDATE [dbo].[post] SET [type] = '2' WHERE post_id=14
UPDATE [dbo].[post] SET [type] = '1' WHERE post_id=15
UPDATE [dbo].[post] SET [type] = '2' WHERE post_id=16
UPDATE [dbo].[post] SET [type] = '2' WHERE post_id=17
UPDATE [dbo].[post] SET [type] = '4' WHERE post_id=18
UPDATE [dbo].[post] SET [type] = '1' WHERE post_id=19
UPDATE [dbo].[post] SET [type] = '4' WHERE post_id=20
UPDATE [dbo].[post] SET [type] = '4' WHERE post_id=21
UPDATE [dbo].[post] SET [type] = '4' WHERE post_id=22
UPDATE [dbo].[post] SET [type] = '2' WHERE post_id=23
UPDATE [dbo].[post] SET [type] = '1' WHERE post_id=24
UPDATE [dbo].[post] SET [type] = '3' WHERE post_id=25
UPDATE [dbo].[post] SET [type] = '2' WHERE post_id=26
UPDATE [dbo].[post] SET [type] = '3' WHERE post_id=27
UPDATE [dbo].[post] SET [type] = '3' WHERE post_id=28
UPDATE [dbo].[post] SET [type] = '4' WHERE post_id=29
UPDATE [dbo].[post] SET [type] = '1' WHERE post_id=30
